-- triggers 
    -- triggers are like a block of code that will automatically execute when an event happans
    -- for example if there is any insert,update or delete then they are events
    -- if we want something to happan automatically every time an event occurs we use triggers
    -- these triggers are stored in the database

    -- these are benificial for audit logging
    -- keepping record of who made changes and when 
    -- synchronising multiple tables
    -- creating backup before any event



-- create table emp_copy as 
-- select employee_id,first_name from hr.EMPLOYEES where employee_id between 100 and 105;








-- syntax :- 

-- create or replace trigger trg1
-- before INSERT
-- on emp_copy

-- begin 
--     DBMS_OUTPUT.PUT_LINE('trigger called before the insert statement');
-- end;

-- insert into EMP_COPY VALUES(107,'abs');








-- create or replace trigger trg2
-- after update
-- on emp_copy

-- begin 
--     DBMS_OUTPUT.PUT_LINE('trigger called after the update statement');
-- end;

-- UPDATE EMP_COPY set first_name = 'yash';









-- but these are statement triggers 
-- and they only run after completion of the whole work 
-- but if we want our trigger to run after each update 
-- we use  --row trigger--  which will run for each row 
-- we use the keyword 'for each row'





-- create or replace trigger trg3
-- after update
-- on emp_copy
-- for each row

-- begin 
--     DBMS_OUTPUT.PUT_LINE('trigger called after the update statement');
-- end;

-- UPDATE EMP_COPY set first_name = 'aman';













-- now we create a trigger that shows if we inserted or updates 



-- create or replace trigger trg4
-- after update or insert
-- on emp_copy
-- for each row

-- begin 
--     if updating then
--         DBMS_OUTPUT.PUT_LINE('trigger called after the update statement');
--     else 
--         DBMS_OUTPUT.PUT_LINE('trigger called after the insert statement');
--     end if;
-- end;

-- UPDATE EMP_COPY set first_name = 'aman';
-- insert into EMP_COPY VALUES(110,'xyz');






-- CREATE TABLE audits (
--       audit_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--       table_name       VARCHAR2(255),
--       transaction_name VARCHAR2(10),
--       by_user          VARCHAR2(30),
--       transaction_date DATE
-- );



-- create or replace trigger trg5
-- after update or insert or delete
-- on emp_copy
-- for each row

-- declare 
--     l_transection VARCHAR2(20);

-- begin 
--     if updating then
--         l_transection := 'update';
--             DBMS_OUTPUT.put_line(:OLD.first_name || '  ' || :new.first_name);
--     elsif deleting then
--         l_transection := 'delete';
--     else 
--         l_transection := 'insert';
--     end if;

--     INSERT INTO audits (table_name, transaction_name, by_user, transaction_date)
--     VALUES('emp_copy',l_transection, USER, SYSDATE);

-- end;




-- insert into EMP_COPY VALUES(111,'mahi');
-- UPDATE EMP_COPY set first_name = 'jar' where employee_id = 105;
-- select * from AUDITS;
















CREATE TABLE namechanger (
      audit_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      table_name       VARCHAR2(255),
      odlname VARCHAR2(10),
      newname VARCHAR2(10),
      by_user          VARCHAR2(30),
      transaction_date DATE
);





-- -- CREATE  TABLE namechanger (
-- --       audit_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
-- --       table_name       VARCHAR2(255),
-- --       oldname VARCHAR2(10),
-- --       newname VARCHAR2(10),
-- --       by_user          VARCHAR2(30),
-- --       transaction_date DATE
-- -- );





-- create or replace trigger trg6
-- after update 
-- on emp_copy
-- for each row

-- declare 
--     l_transection VARCHAR2(20);
--     old_name varchar(20);
--     new_name varchar (20);

-- begin 

--     l_transection := 'update';
--     old_name := :old.first_name;
--     new_name := :new.first_name;



--     INSERT INTO NAMECHANGER (table_name,oldname,newname, by_user, transaction_date)
--     VALUES('emp_copy',old_name,new_name, USER, SYSDATE);

-- end;




UPDATE EMP_COPY set first_name = 'jar' where employee_id = 105;
SELECT * from NAMECHANGER;





