
-- drop table logininfo;

CREATE TABLE logininfo (
       audit_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       table_name       VARCHAR2(255),
       user_name          varchar2(20),
       event_type      varchar2(20),
       event_date DATE
);



create or replace trigger trg7
before logon or logoff
on database

declare 
     e_type VARCHAR2(20);
    e_name varchar2(20);
begin 
    IF (ORA_SYSEVENT = 'LOGON') THEN
        e_type := 'LOGIN';
    ELSIF (ORA_SYSEVENT = 'LOGOFF') THEN
        e_type := 'LOGOUT';
    END IF;

    e_name := user;

    INSERT INTO logininfo (table_name,user_name, event_type,event_date)
    VALUES('logininfo',e_name , e_type , SYSDATE);

end;

